CREATE TABLE ACTIVITY (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME VARCHAR(1000),
  DESC VARCHAR(3000),
  DATE TEXT
);

CREATE TABLE FIN (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ACT_ID INTEGER,
  NAME VARCHAR(1000),
  DESC VARCHAR(3000),
  AMOUNT NUMERIC(10, 2)
);

-- Example 1: 插花
INSERT INTO ACTIVITY(ID, NAME, DESC, DATE)
VALUES(1, '插花', '萱萱爸爸教大家如何插花，做出一小瓶花艺。', '2019-03-21');
INSERT INTO FIN(ACT_ID, NAME, DESC, AMOUNT)
VALUES(1, '花', '花的开销', 300);
INSERT INTO FIN(ACT_ID, NAME, DESC, AMOUNT)
VALUES(1, '花瓶', '花瓶的开销', 400);
INSERT INTO FIN(ACT_ID, NAME, DESC, AMOUNT)
VALUES(1, '泥土', '泥土的开销', 200);

-- Example 2: 春游
INSERT INTO ACTIVITY(ID, NAME, DESC, DATE)
VALUES(2, '春游', '幼儿园大家一起去春游。', '2019-04-28');
INSERT INTO FIN(ACT_ID, NAME, DESC, AMOUNT)
VALUES(2, '路费', '大巴的费用', 1000);
INSERT INTO FIN(ACT_ID, NAME, DESC, AMOUNT)
VALUES(2, '门票', '公园门票开销', 1700);
INSERT INTO FIN(ACT_ID, NAME, DESC, AMOUNT)
VALUES(2, '餐饮', '午饭以及零食的开销', 2000);
